### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Ryuuu297** [Unwork-ID/Neo-Akairo#39]
Configure LavaServer on src/EreleConnector/nodes.ts
There is no such folder src/EreleConnector/nodes.ts ?
Can u help me ?

**Comment by tokisaki13** [comment]
i have change all config on src/config.ts.
i'll update readme soon, thank you

**Comment by tokisaki13** [comment]
> Configure LavaServer on src/EreleConnector/nodes.ts
> There is no such folder src/EreleConnector/nodes.ts ?
> Can u help me ?

i have change all config on src/config.ts.
i'll update readme soon, thank you

**Comment by Ryuuu297** [comment]
> > Configure LavaServer on src/EreleConnector/nodes.ts
> > There is no such folder src/EreleConnector/nodes.ts ?
> > Can u help me ?
> 
> i have change all config on src/config.ts.
> i'll update readme soon, thank you

Ty

**Comment by tokisaki13** [comment]
> > > Configure LavaServer on src/EreleConnector/nodes.ts
> > > There is no such folder src/EreleConnector/nodes.ts ?
> > > Can u help me ?
> > 
> > 
> > i have change all config on src/config.ts.
> > i'll update readme soon, thank you
> 
> Ty

anytime
