### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by Ryuuu297** [Unwork-ID/Neo-Akairo#41]
I follow the readme.md but it doesn't work
Os : Parrot os Linux 
Can u help me ?

**Comment by tokisaki13** [comment]
join on our support server, in link README,

**Comment by tokisaki13** [comment]
> I follow the readme.md but it doesn't work
> Os : Parrot os Linux
> Can u help me ?

@Ryuuu297 you can mention me on My discord server. join and ask in #chatting channel
